// Title: Admin Users Localization
// Path: src/localization/en/admin-users.ts
// Functionality: English localization strings for application screens, actions, and empty states.

export const adminUsers = {
  pageTitle: 'Identity Directory',
  pageDescription: 'Manage resident identities, unit assignments, and access levels.',
  unavailableTitle: 'Identity directory unavailable',
  unavailableDescription: 'User records could not be loaded.',
  criticalLoadError: 'Critical failure loading directory.',
  operationFailed: 'Operation failed.',
  signatureFailed: 'Signature failed.',
  internalException: 'Internal exception.',
  permissionsUpdatedToast: 'Permissions updated.',
  accountCreatedToast: 'Account created. Supabase invitation email sent.',
  createAccountError: 'Account could not be created.',
  bulkOperationToast: 'Bulk operation executed.',
  accountStatusToast: (status: string) => `Account ${status}.`,
  defaultPendingReason: 'Identity verified.',
  statusLabel: (status: string) => status === 'approved' ? 'Active' : status.replace('_', ' '),
  searchAria: 'Search users by name, email, or phone',
  searchPlaceholder: 'Name, Email, Phone...',
  filterRoleAria: 'Filter by role',
  filterStatusAria: 'Filter by status',
  summaryAria: 'Identity directory summary',
  summary: {
    loaded: 'Loaded identities',
    selected: 'Selected',
    units: 'Units',
  },
  filters: {
    allRoles: 'All Roles',
    residents: 'Residents',
    admins: 'Admins',
    allStatuses: 'All Statuses',
    active: 'Active',
    pending: 'Pending',
    suspended: 'Suspended',
  },
  selectAllRows: 'Select all rows',
  selectUser: (label: string) => `Select ${label}`,
  userFallback: 'user',
  headers: {
    identity: 'Identity',
    assignment: 'Assignment',
    levelStatus: 'Level & Status',
    actions: 'Actions',
  },
  noName: 'No Name',
  unitPrefix: 'Unit',
  unassigned: 'Unassigned',
  manager: 'Manager',
  settings: 'Settings',
  createAccount: 'Create Account',
  creatingAccount: 'Creating...',
  closeCreateAccount: 'Close account creation',
  createFields: {
    fullName: 'Full Name',
    fullNamePlaceholder: 'Resident name',
    email: 'Email Address',
    emailPlaceholder: 'resident@example.com',
    inviteDelivery: 'Supabase will email a secure invitation link. The user will choose their own password.',
    role: 'Account Role',
    apartment: 'Apartment',
    selectApartment: 'Select apartment',
    adminConfirmation: 'Confirm Superadmin Password',
  },
  emptyTitle: 'No records found',
  emptyDescription: 'No identities match the current filters. Try adjusting your search, role, or status.',
  querying: 'Querying...',
  loadMore: 'Load More Results',
  selected: 'Selected',
  approve: 'Approve',
  reject: 'Reject',
  suspend: 'Suspend',
  roleChange: 'Role Change',
  massActionTitle: 'Mass Account Action',
  massActionDescription: (count: number) => `Applying change to ${count} identities.`,
  residentRole: 'Resident',
  adminRole: 'Admin',
  auditReason: 'Audit Reason (Required)',
  auditReasonRequired: 'An audit reason is required.',
  auditReasonPlaceholder: '...',
  cancel: 'Cancel',
  execute: 'Execute',
  identityConfigTitle: 'Identity Configuration',
  lifecycleControl: 'Lifecycle Control',
  operationalReasonPlaceholder: 'Operational reason...',
  activate: 'Activate',
  unitAuthorization: 'Unit Authorization',
  noUnitAssigned: 'No Unit Assigned',
  systemPrivileges: 'System Privileges',
  assignManager: 'Assign as Apartment Manager',
  securitySignatureRequired: 'Security Signature Required',
  adminPasswordPlaceholder: 'Admin Password',
  applyIdentityChange: 'Apply Identity Transformation',
  revokeTitle: 'Revoke Access',
  revokeDescription: (email: string | null) => `Terminate session for ${email} immediately?`,
  confirmRevocation: 'Confirm Revocation',
} as const;
