// Title: Admin Notices Localization
// Path: src/localization/en/admin-notices.ts
// Functionality: English localization strings for application screens, actions, and empty states.

import { noticeMessages } from './notices';

export const adminNotices = {
  pageTitle: 'Notices',
  pageDescription: 'Send in-app notices to residents and review what has been sent.',
  unavailableTitle: 'Notices unavailable',
  unavailableDescription: 'Notices could not be loaded. Apply migration 0057 and try again.',
  composeTitle: 'Compose',
  audienceLabel: 'Audience',
  audiences: {
    all: 'All residents',
    apartment: 'By apartment',
    profile: 'One resident',
  },
  apartmentLabel: 'Apartment',
  apartmentAria: 'Apartment',
  apartmentPlaceholder: 'Select an apartment...',
  residentLabel: 'Resident',
  residentAria: 'Resident',
  residentPlaceholder: 'Select a resident...',
  unitPrefix: 'Unit',
  typeLabel: 'Type',
  typeAria: 'Notice type',
  noticeTypeLabels: noticeMessages.typeLabels,
  titleLabel: 'Title',
  titlePlaceholder: 'e.g. Garage construction notice',
  messageLabel: 'Message',
  messagePlaceholder: 'Write the notice residents will see...',
  sendNotice: 'Send notice',
  sending: 'Sending...',
  sendError: 'Failed to send notice.',
  sentToast: (count: number) => `Notice sent to ${count} resident(s).`,
  sentTitle: (count: number) => `Sent (${count})`,
  emptyTitle: 'Nothing sent yet',
  emptyDescription: 'Notices you send will appear here.',
  recipients: (count: number) => `${count} recipient${count === 1 ? '' : 's'}`,
  readCount: (read: number, recipients: number) => `${read}/${recipients} read`,
  resendButton: 'Edit & resend',
  resendAria: (title: string) => `Edit and resend notice: ${title}`,
  openEditor: 'Open editor',
  editorTitle: 'Compose notice',
  editorSave: 'Save',
  editorCancel: 'Cancel',
  portalBanner: {
    title: 'Resident portal banner',
    description: 'A persistent message pinned to the top of every resident dashboard. Use it for building-wide operational notices. Leave it empty to hide the banner.',
    placeholder: 'e.g. Garage deep-clean on the first Monday of each month - move vehicles by 8 AM.',
    live: 'Live on dashboards',
    hidden: 'Not shown',
    save: 'Publish banner',
    saving: 'Publishing...',
    clear: 'Clear',
    saved: 'Portal banner updated.',
    saveError: 'Failed to update the portal banner.',
  },
  actionErrors: {
    selectApartment: 'Select an apartment.',
    selectResident: 'Select a resident.',
    invalidAudience: 'Select a notice audience.',
    invalidType: 'Select a valid notice type.',
    titleBodyRequired: 'Title and body are required.',
    sendNotice: 'Failed to send notice.',
    loadNotices: 'Failed to load notices.',
    loadUnits: 'Failed to load notice units.',
    loadRecipients: 'Failed to load notice recipients.',
    markRead: 'Failed to mark notice as read.',
    markAllRead: 'Failed to mark notices as read.',
  },
} as const;
