// Title: Admin Approvals Localization
// Path: src/localization/en/admin-approvals.ts
// Functionality: English localization strings for application screens, actions, and empty states.

export const adminApprovals = {
  pageTitle: 'Approval Center',
  pageDescription: 'Review account requests and incoming vehicle additions.',
  unavailableTitle: 'Approvals unavailable',
  unavailableDescription: 'Approvals queue could not be loaded.',
  loadError: 'Failed to load approvals queue.',
  addRequest: 'Add vehicle request',
  summaryAria: 'Approval queue summary',
  tabsAria: 'Approval queue type',
  summary: {
    accounts: 'Pending accounts',
    vehicles: 'Pending vehicles',
    units: 'Units available',
  },
  tabs: {
    accounts: 'Accounts',
    vehicles: 'Vehicles',
  },
  table: {
    userDetails: 'User Details',
    contextAssignment: 'Context / Assignment',
    vehicleDetails: 'Vehicle Details',
    linkedUnit: 'Linked Unit',
    actions: 'Actions',
  },
  selectAllAccounts: 'Select all accounts',
  selectAllVehicles: 'Select all vehicles',
  selectAccount: (label: string) => `Select ${label}`,
  selectVehicle: (plate: string) => `Select vehicle ${plate}`,
  unnamedAccount: 'account',
  unnamed: 'Unnamed',
  requestPrefix: 'Req:',
  unitPrefix: 'Unit',
  apartmentPrefix: 'Apt',
  unknownApartment: 'Unknown',
  ownerNotSpecified: 'Owner not specified',
  approve: 'Approve',
  reject: 'Reject',
  selected: 'Selected',
  bulkSelectionAria: 'Bulk approval selection',
  emptyAccountsTitle: 'All caught up',
  emptyAccountsDescription: 'There are no pending account requests right now.',
  emptyVehiclesTitle: 'Vehicle queue is empty',
  emptyVehiclesDescription: 'No pending vehicle requests to review.',
  defaultReasons: {
    accountApproval: 'Account verified and assigned',
    accountRejection: 'Admin rejection',
    vehicleApproval: 'Manual admin approval',
    vehicleRejection: 'Admin rejection',
  },
  accountApprovedToast: 'Account approved.',
  accountRejectedToast: 'Account rejected.',
  vehicleApprovedToast: 'Vehicle approved.',
  vehicleRejectedToast: 'Vehicle request rejected.',
  vehicleSubmittedToast: 'Vehicle request submitted to queue.',
  approvalError: 'Failed to process approval.',
  rejectAccountError: 'Failed to reject account.',
  approveVehicleError: 'Approval failed.',
  rejectVehicleError: 'Rejection failed.',
  submitVehicleError: 'Failed to submit request.',
  bulkApproveAccountsToast: (count: number) => `Successfully approved ${count} accounts.`,
  bulkRejectAccountsToast: (count: number) => `Successfully rejected ${count} accounts.`,
  bulkVehiclesToast: (intent: string, count: number) => `Successfully ${intent} ${count} vehicles.`,
  bulkApproveAccountsError: 'Failed to bulk approve accounts.',
  bulkRejectAccountsError: 'Failed to bulk reject accounts.',
  bulkVehiclesError: 'Bulk operation failed.',
  rejectModalTitle: 'Reject Request',
  rejectModalDescription: 'Reason for rejection will be securely logged.',
  rejectionReason: 'Rejection Reason',
  rejectionPlaceholder: 'e.g., Document missing',
  cancel: 'Cancel',
  confirmReject: 'Confirm Reject',
  rejecting: 'Rejecting...',
  bulkModalTitle: 'Bulk Action',
  bulkModalDescription: (count: number) => `Processing ${count} items.`,
  resolutionLog: 'Resolution Log (Required)',
  bulkReasonPlaceholder: 'Reason for bulk operation...',
  confirm: 'Confirm',
  processing: 'Processing...',
  clearSelection: 'Clear selection',
  addVehicleRequestTitle: 'Add Vehicle Request',
} as const;
