// Title: Admin Disruptions Localization
// Path: src/localization/en/admin-disruptions.ts
// Functionality: English localization strings for application screens, actions, and empty states.

export const adminDisruptions = {
  navTitle: 'Disruptions',
  pageTitle: 'Construction & Disruptions',
  pageDescription: 'Block zones for construction, auto-relocate affected vehicles, and return them when done.',
  unavailableTitle: 'Disruptions unavailable',
  unavailableDescription: 'Construction disruption data could not be loaded.',
  newDisruption: 'New disruption',
  editDisruption: 'Edit disruption',
  editButton: 'Edit',
  summaryAria: 'Disruption workflow summary',
  summary: {
    scheduled: 'Scheduled',
    active: 'Active',
    reviewNeeded: 'Review needed',
    completed: 'Completed',
  },
  sections: {
    scheduled: 'Scheduled',
    active: 'Active',
    reviewNeeded: 'Review needed',
    activeScheduled: 'Active & scheduled',
    completed: 'Completed',
  },
  emptyCurrentTitle: 'No current disruption work',
  emptyCurrentDescription: 'There are no scheduled, active, or review-needed disruptions right now.',
  emptyActiveTitle: 'No active disruptions',
  emptyActiveDescription: 'Create one to block a construction zone and relocate affected vehicles.',
  statusLabels: {
    scheduled: 'scheduled',
    active: 'active',
    completed: 'completed',
    cancelled: 'cancelled',
  },
  countLabels: {
    blocked: (count: number) => `${count} blocked`,
    relocated: (count: number) => `${count} relocated`,
    awaitingPlacement: (count: number) => `${count} awaiting placement`,
    needReview: (count: number) => `${count} need review`,
    spots: (count: number) => `${count} spots`,
  },
  dateRangeSeparator: 'to',
  createdToast: (blocked: number, relocated: number, needsPlacement: number) =>
    `Disruption created - ${blocked} blocked, ${relocated} relocated, ${needsPlacement} awaiting placement.`,
  createdScheduledToast: (spots: number, startDate: string) =>
    `Disruption scheduled for ${startDate} - ${spots} spot${spots === 1 ? '' : 's'} reserved for activation.`,
  activatedToast: (blocked: number, relocated: number, needsPlacement: number) =>
    `Disruption activated - ${blocked} blocked, ${relocated} relocated, ${needsPlacement} awaiting placement.`,
  completedToast: (returned: number, needsReview: number) =>
    `Disruption completed - ${returned} returned, ${needsReview} need review.`,
  cancelledToast: 'Scheduled disruption cancelled.',
  updatedToast: 'Scheduled disruption updated.',
  loadError: 'Failed to load disruptions.',
  createError: 'Failed to create disruption.',
  activateError: 'Failed to activate disruption.',
  completeError: 'Failed to complete disruption.',
  cancelError: 'Failed to cancel disruption.',
  updateError: 'Failed to update disruption.',
  saveChanges: 'Save changes',
  close: 'Close',
  fields: {
    title: 'Title',
    constructionStart: 'Construction start',
    constructionEnd: 'Construction end',
    reason: 'Reason',
    spotsToBlock: 'Spots to block',
  },
  placeholders: {
    title: 'e.g. Garage Level 2 Construction',
    reason: 'What is happening and why are these spots blocked?',
  },
  floorLabels: {
    street: 'Street',
    floorAbbreviation: (floor: string) => `Fl ${floor}`,
    generalZone: 'General',
  },
  zoneLabel: 'Zone:',
  selection: {
    clearFloor: 'Clear floor',
    selectFloor: 'Select floor',
    clearAll: 'Clear all',
    rangeHint: 'Shift+click to select range',
    selected: (count: number) => `${count} selected`,
    occupied: (count: number) => `${count} occupied`,
    noBlockableSpots: 'No blockable spots on this floor.',
  },
  occupiedWarning: (count: number) =>
    `${count} occupied spot${count > 1 ? 's' : ''} will be relocated to available spots automatically. Any without room go to awaiting placement.`,
  zoneTitle: (zone: string) => `Zone: ${zone}`,
  cancel: 'Cancel',
  blockSpotsNow: (count: number) => `Block ${count} spot${count === 1 ? '' : 's'} now`,
  scheduleSpots: (count: number) => `Schedule ${count} spot${count === 1 ? '' : 's'}`,
  activateNow: 'Activate',
  cancelScheduled: 'Cancel scheduled',
  completeAndReturn: 'Complete & return',
  actionErrors: {
    selectSpots: 'Select at least one spot to block.',
    titleRequired: 'A disruption title is required.',
    reasonRequired: 'A detailed reason is required.',
    invalidDateRange: 'End date must be on or after the start date.',
    loadDisruptions: 'Failed to load disruptions.',
    loadRelocations: 'Failed to load disruption relocations.',
    loadSpots: 'Failed to load disruption spots.',
    loadParkingSpots: 'Failed to load parking spots for disruptions.',
    createDisruption: 'Failed to create disruption.',
    activateDisruption: 'Failed to activate disruption.',
    activateDueDisruptions: 'Failed to activate due disruptions.',
    completeDisruption: 'Failed to complete disruption.',
    cancelDisruption: 'Failed to cancel disruption.',
    updateDisruption: 'Failed to update disruption.',
  },
} as const;
