// Title: Admin Apartments Localization
// Path: src/localization/en/admin-apartments.ts
// Functionality: English localization strings for application screens, actions, and empty states.

export const adminApartments = {
  pageTitle: 'Property Directory',
  pageDescription: 'Review units, occupancy, linked vehicles, and operational status.',
  unavailableTitle: 'Property directory unavailable',
  unavailableDescription: 'Apartment data could not be loaded.',
  searchAria: 'Search units by number',
  searchPlaceholder: 'Search Unit #...',
  filterAria: 'Filter by status',
  allStatuses: 'All Statuses',
  statusLabels: {
    vacant:     'Vacant',
    occupied:   'Occupied',
    problem:    'Problem',
    restricted: 'Restricted',
  },
  visualMap: 'Visual Map',
  listView: 'List View',
  summaryAria: 'Property directory summary',
  summary: {
    total: 'Total units',
    occupied: 'Occupied',
    vacant: 'Vacant',
  },
  emptyTitle: 'No units found',
  emptyDescription: 'No apartments match your search or filter.',
  penthouseLevel: 'Penthouse Level',
  floorLabel: (floor: string) => `Floor ${floor}`,
  unitHeader: 'Unit #',
  statusHeader: 'Status',
  occupantsHeader: 'Occupants',
  vehiclesHeader: 'Vehicles',
  viewHeader: 'View',
  unitPrefix: 'Unit',
  residentsCount: (count: number) => `${count} residents`,
  permitsCount: (count: number) => `${count} permits`,
  details: 'Details',
  detailDrawerLabel: 'Apartment details',
  loadingProfile: 'Loading Unit Profile...',
  quickStatusOverride: 'Quick Status Override',
  setVacant: 'Set Vacant',
  setOccupied: 'Set Occupied',
  reportProblem: 'Report Problem',
  setRestricted: 'Set Restricted',
  registeredOccupants: 'Registered Occupants',
  authorizedVehicles: 'Authorized Vehicles',
  assignedParkingSpots: 'Assigned Parking Spots',
  activeIncidents: 'Active Incidents',
  eventTimeline: 'Unit Event Timeline',
  noName: 'No Name',
  unknown: 'unknown',
  noResidents: 'No residents linked to this unit.',
  noVehicles: 'No vehicles registered.',
  noParkingSpots: 'No parking spots linked to this unit.',
  noActiveIncidents: 'No active incidents linked to this unit.',
  noEvents: 'No historical events recorded.',
  loadDetailsError: 'Failed to fetch apartment details.',
  updateStatusTitle: 'Update Status',
  updateStatusDescription: (status: string | null) => `Changing unit status to ${status}. This action is logged.`,
  operationalReason: 'Operational Reason (Required)',
  statusReasonPlaceholder: 'e.g. Unit sold, resident moved, flooded...',
  cancel: 'Cancel',
  confirmChange: 'Confirm Change',
  statusUpdateError: 'Failed to update status.',
  statusUpdatedToast: (status: string) => `Status securely updated to ${status}`,
  unexpectedError: 'An unexpected error occurred.',
  titles: {
    occupants: 'Occupants',
    vehicles: 'Vehicles',
  },
} as const;
