// Title: Admin Vehicles Localization
// Path: src/localization/en/admin-vehicles.ts
// Functionality: English localization strings for application screens, actions, and empty states.

export const adminVehicles = {
  pageTitle: 'Vehicle Directory',
  unavailableTitle: 'Vehicles unavailable',
  unavailableDescription: 'Vehicle data could not be loaded.',
  loadError: 'Failed to load directory.',
  addError: 'Failed to add vehicle.',
  updateError: 'Failed to update status.',
  archiveError: 'Failed to archive vehicle.',
  registeredToast: 'Vehicle securely registered to the unit.',
  archivedToast: 'Vehicle archived successfully.',
  markedToast: (status: string) => `Vehicle marked as ${status}.`,
  defaultReasons: {
    rejection: 'Manual admin rejection',
    override: 'Manual override',
    archive: 'Admin archived',
  },
  registerVehicle: 'Register Vehicle',
  searchAria: 'Search vehicles by plate, unit, or owner',
  searchPlaceholder: 'Search by plate, unit, or owner...',
  filterAria: 'Filter by status',
  filters: {
    all: 'All (Excl. Archived)',
    active: 'Active',
    pending: 'Pending',
    rejected: 'Rejected',
    archived: 'Archived',
  },
  headers: {
    identification: 'Identification',
    unitOwner: 'Unit / Owner',
    status: 'Status',
    actions: 'Actions',
  },
  apartmentPrefix: 'Apt',
  unknownApartment: 'Unknown',
  notAssigned: 'Not assigned',
  statusLabels: {
    approved: 'Active',
    pending_approval: 'Pending',
    rejected: 'Rejected',
    archived: 'Archived',
  },
  info: 'Info',
  emptyTitle: 'No vehicles found',
  emptyDescription: 'No vehicles match your search or filter.',
  modalTitle: 'Vehicle Details',
  plateNumber: 'Plate Number',
  makeModel: 'Make & Model',
  statusLabel: 'Lifecycle status',
  yearLabel: 'Year',
  colorLabel: 'Color',
  assignmentLabel: 'Parking assignment',
  currentSpot: (spot: string) => `Spot ${spot}`,
  spotLocation: (floor: string, zone: string) => `Floor ${floor} / Zone ${zone}`,
  noSpotAssigned: 'No active spot assignment',
  lastActionNote: 'Last action note',
  noActionNote: 'No note recorded for the latest action.',
  vehicleRecord: 'Vehicle record',
  linkedUnitOwner: 'Linked Unit & Owner',
  apartmentLabel: 'Apartment:',
  notAvailable: 'N/A',
  adminNotePlaceholder: 'Optional admin note',
  adminNoteAria: 'Admin action note',
  approve: 'Approve',
  reject: 'Reject',
  moveToArchive: 'Move to Archive',
  dismiss: 'Dismiss',
} as const;
