// Title: Admin Issues Localization
// Path: src/localization/en/admin-issues.ts
// Functionality: English localization strings for application screens, actions, and empty states.

export const adminIssues = {
  pageTitle: 'Parking Issues',
  pageDescription: 'Triage resident reports, track workflow status, and clear conflict flags when resolved.',
  unavailableTitle: 'Issues unavailable',
  unavailableDescription: 'Parking issues could not be loaded. Apply migration 0058 and try again.',
  updateError: 'Failed to update issue.',
  updatedToast: 'Parking issue updated.',
  searchPlaceholder: 'Search spot, plate, resident, unit, or note...',
  searchLabel: 'Search',
  searchAria: 'Search parking issues',
  filtersAria: 'Parking issue filters',
  filterAria: 'Filter by status',
  statusFilterLabel: 'Status',
  allStatuses: 'All statuses',
  timeFilters: {
    basisLabel: 'Date type',
    basisAria: 'Filter issues by date type',
    presetLabel: 'Window',
    presetAria: 'Filter issues by time window',
    customFromLabel: 'From',
    customFromAria: 'Filter issues from date',
    customToLabel: 'To',
    customToAria: 'Filter issues to date',
    basis: {
      reported: 'Reported date',
      resolved: 'Resolved date',
    },
    presets: {
      all: 'All time',
      today: 'Today',
      last7Days: 'Last 7 days',
      last30Days: 'Last 30 days',
      custom: 'Custom',
    },
  },
  summaryAria: 'Parking issue queue summary',
  summary: {
    activeConflicts: 'Active conflicts',
  },
  conflictBadge: (count: number) => `${count} active on this spot`,
  timeline: {
    reported: 'Reported',
    current: 'Current',
    resolved: 'Resolved',
  },
  emptyTitle: 'No issues found',
  emptyDescription: 'No parking issues match the current filters.',
  noResidentNote: 'No resident note provided.',
  spotPrefix: 'Spot',
  unitPrefix: 'Unit',
  unknown: 'Unknown',
  residentFallback: 'Resident',
  detailTitle: 'Issue Detail',
  closeAria: 'Close',
  meta: {
    reporter: 'Reporter',
    unit: 'Unit',
    violationPlate: 'Violation plate',
    spotStatus: 'Spot status',
    location: 'Location',
    reportedAt: 'Reported at',
    currentStatus: 'Current status',
  },
  notProvided: 'Not provided',
  reportTitle: 'Resident report',
  noComment: 'No comment provided.',
  lifecycleTitle: 'Issue lifecycle',
  workflowStatus: 'Workflow status',
  resolutionNote: 'Resolution / internal note',
  resolutionPlaceholder: 'What did the admin do?',
  resolutionRequirement: (minLength: number, status: string) => `Add at least ${minLength} characters before marking this issue ${status}.`,
  cancel: 'Cancel',
  saveStatus: 'Save status',
  statusLabels: {
    open: 'Open',
    in_progress: 'In progress',
    resolved: 'Resolved',
    closed: 'Closed',
  },
  actionErrors: {
    loadIssues: 'Failed to load parking issues.',
    loadSpots: 'Failed to load issue parking spots.',
    loadProfiles: 'Failed to load issue profiles.',
    loadUnits: 'Failed to load issue units.',
    issueIdRequired: 'Issue id is required.',
    invalidIssueType: 'Invalid issue type.',
    invalidStatus: 'Invalid issue status.',
    resolutionRequired: 'Resolution note is required.',
    reportIssue: 'Failed to file parking issue.',
    updateIssue: 'Failed to update parking issue.',
  },
} as const;
