// Title: Auth Localization
// Path: src/localization/en/auth.ts
// Functionality: English localization strings for authentication screens, actions, and empty states.

export const auth = {
  emailLabel: 'Email Address',
  emailPlaceholder: 'name@example.com',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Enter your password',
  passwordPolicyPlaceholder: 'Min 8 chars, 1 uppercase, 1 number',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  unexpectedError: 'An unexpected error occurred',
  passwordPolicyError: 'Password must be at least 8 characters long and include a number and an uppercase letter.',
  termsOfService: 'Terms of Service',
  privacyPolicy: 'Privacy Policy',
  login: {
    title: 'Welcome Back',
    description: 'Sign in to your ResidentPark account',
    forgotPassword: 'Forgot password?',
    invalidCredentials: 'Invalid email or password',
    loading: 'Authenticating...',
    submit: 'Sign In',
    needAccount: 'Need an account?',
    registerRequest: 'Register Request',
    backToHome: 'Back to home',
  },
  register: {
    title: 'Request Account',
    description: 'Submit a request to access ResidentPark',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'John Doe',
    termsError: 'You must agree to the Terms of Service and Privacy Policy.',
    termsPrefix: 'I agree to the',
    termsLink: 'Terms of Service',
    privacyJoiner: 'and',
    privacyLink: 'Privacy Policy',
    termsSuffix: 'I understand this account requires administrator approval.',
    loading: 'Submitting Request...',
    submit: 'Submit Request',
    hasAccount: 'Already have an account?',
    signIn: 'Sign In',
    strengthLabels: {
      0: '',
      1: 'Weak',
      2: 'Fair',
      3: 'Strong',
    },
  },
  forgotPassword: {
    title: 'Reset Password',
    description: 'Enter your email and we will send a secure reset link.',
    sendError: 'Unable to send reset instructions.',
    sent: 'If an account exists for that email, a reset link will be sent.',
    loading: 'Sending...',
    submit: 'Send Reset Link',
    backToSignIn: 'Back to Sign In',
  },
  resetPassword: {
    title: 'Choose New Password',
    description: 'Use the secure invitation or reset link from your email to choose your password.',
    newPasswordLabel: 'New Password',
    confirmPasswordLabel: 'Confirm Password',
    confirmPasswordPlaceholder: 'Repeat your new password',
    mismatchError: 'Passwords do not match.',
    updateError: 'Unable to update your password.',
    success: 'Your password has been updated. You can sign in again.',
    loading: 'Updating...',
    submit: 'Update Password',
  },
} as const;
