// Title: Invitations Localization
// Path: src/localization/en/invitations.ts
// Functionality: English localization strings for invitation screens, actions, and empty states.

export const invitations = {
  pageTitle: 'Invitations',
  pageDescription: 'Create invite records, share token-bound accept-links, and track acceptance without implying email delivery.',
  unavailableTitle: 'Invitations unavailable',
  unavailableDescription: 'Invitation data could not be loaded.',
  manualDeliveryBadge: 'Manual link delivery',
  summaryAria: 'Invitation summary',
  summary: {
    visible: 'Visible records',
    pending: 'Ready to share',
    accepted: 'Accepted',
    closed: 'Expired or revoked',
  },
  tabsAria: 'Invitation workflow',
  tabs: {
    import: 'Bulk Import',
    importDescription: 'Create invitation rows from email and unit pairs.',
    directory: 'Invitation Directory',
    directoryDescription: 'Copy links and track delivery and acceptance state.',
  },
  dataInputTitle: 'Create invite records',
  dataInputFormatLabel: 'Format:',
  dataInputFormat: 'email, apartment_number',
  importInputAria: 'Invitation rows',
  placeholder: 'john@example.com, A-101',
  sendButton: 'Create invitations',
  deliveryModelTitle: 'Delivery model',
  deliveryModelDescription: 'This tool creates database invitations and secure accept-links. It does not send email by itself.',
  deliveryModelSteps: [
    { label: 'Create', value: 'Import rows to create pending invitation records.' },
    { label: 'Share', value: 'Copy the accept-link from the directory and send it through an approved channel.' },
    { label: 'Accept', value: 'The resident must use the token and sign in with the invited email.' },
  ],
  reportTitle: 'Import report',
  processedLabel: 'Processed',
  successLabel: 'Created',
  failedLabel: 'Failed',
  errorsLabel: 'Errors',
  createdToast: (count: number) => `${count} invitation ${count === 1 ? 'record was' : 'records were'} created. Copy links from the directory before sharing.`,
  missingColumns: 'Missing columns',
  rowLabel: (row: number) => `Row ${row}`,
  directoryTitle: 'Invitation Directory',
  directoryDescription: 'Delivery shows whether a copyable link exists; consumption shows whether the invited account has accepted it.',
  searchPlaceholder: 'Search email...',
  searchAria: 'Search invitations by email',
  statusFilterAria: 'Filter by status',
  allStatuses: 'All Statuses',
  statusLabels: {
    pending:  'Pending',
    accepted: 'Accepted',
    expired:  'Expired',
    revoked:  'Revoked',
  },
  deliveryStatus: {
    ready: 'Link ready',
    completed: 'Accepted',
    expired: 'Expired',
    disabled: 'Disabled',
  },
  deliveryDescriptions: {
    pending: 'No email is sent by this screen. Copy and share the accept-link manually.',
    accepted: 'The invite was consumed by the matching email.',
    expired: 'The old link is no longer valid. Refresh it before sharing.',
    revoked: 'The link was disabled by staff and cannot be used.',
  },
  consumptionDescriptions: {
    pending: 'Waiting for the invited email to open the token-bound registration flow.',
    accepted: 'The invitation was consumed and cannot be reused.',
    expired: 'No matching account accepted before the expiry time.',
    revoked: 'Acceptance was stopped before the invite was consumed.',
  },
  loading: 'Loading invitations...',
  emptyTitle: 'No invitations',
  emptyDescription: 'No invitations match your search or filter.',
  detailsHeader: 'Invitee',
  deliveryHeader: 'Delivery',
  consumptionHeader: 'Consumption',
  windowHeader: 'Window',
  actionsHeader: 'Actions',
  apartmentPrefix: 'Apt:',
  roleLabel: 'Role',
  unassignedApartment: 'Unassigned',
  createdPrefix: 'Created:',
  expiresPrefix: 'Expires:',
  revoke: 'Revoke',
  resend: 'Refresh link',
  copyLink: 'Copy link',
  linkCopiedToast: 'Accept-link copied. Share it through the approved channel.',
  linkCopyError: 'Could not copy the link.',
  loadMore: 'Load More',
  revokeTitle: 'Revoke Invitation',
  revokeDescription: 'This link will be permanently disabled.',
  cancel: 'Cancel',
  confirm: 'Confirm',
  revoking: 'Revoking...',
  revokedToast: 'Invitation revoked.',
  resentToast: 'Invitation link refreshed. Copy the current link before sharing.',
  loadError: 'Failed to load invitations.',
  revokeError: 'Failed to revoke invitation.',
  resendError: 'Failed to refresh invitation link.',
  invalidEmail: 'Enter a valid email address.',
  invalidApartmentNumber: 'Enter an apartment number.',
  targetApartmentNotFound: 'Target apartment not found.',
  invitationNotFound: 'Invitation not found.',
  activeInvitationExists: 'An active invitation is already pending for this email.',
  acceptedCannotRevoke: 'An accepted invitation cannot be revoked.',
  acceptedCannotResend: 'An accepted invitation cannot be refreshed.',
  apartmentNotFound: (apartmentNumber: string) => `Apartment '${apartmentNumber}' not found in system`,
  pendingAlreadyExists: 'Pending invitation already exists',
  dbLoadApartmentsError: 'Failed to load apartments for invitations.',
  dbLoadExistingError: 'Failed to load existing invitations.',
  dbCreateError: 'Failed to create invitations.',
  processError: 'Failed to process invitations.',
} as const;
