// Title: Navigation Localization
// Path: src/localization/en/navigation.ts
// Functionality: English localization strings for application screens, actions, and empty states.

import { APP_CONFIG } from '@/config/app';

export const navigation = {
  defaultTitle: APP_CONFIG.shortName,
  home: 'Home',
  notices: 'Notices',
  admin: 'Admin',
  auditLogs: 'Audit Logs',
  adminConsole: 'Admin Console',
  residentPortal: 'Resident Portal',
  commandCenter: 'Command Center',
  adminSections: 'Admin sections',
  adminPanel: {
    title: 'Admin',
    subtitle: 'Workspace',
    expand: 'Expand admin panel',
    collapse: 'Collapse admin panel',
    groups: {
      workspace: 'Workspace',
      operations: 'Operations',
      records: 'Records',
      system: 'System',
    },
  },
  residentNavigation: 'Resident navigation',
  primaryNavigation: 'Primary navigation',
  mobileNavigation: 'Primary navigation',
  more: 'More',
  moreSections: 'More admin sections',
  closeMenu: 'Close menu',
  accountMenu: 'Account menu',
  back: 'Go back',
  signedInAs: 'Signed in as',
  currentSection: 'Current section',
  adminTabs: {
    reports: 'Reports',
    parking: 'Parking',
    approvals: 'Approvals',
    approvalsShort: 'Review',
    issues: 'Parking Issues',
    issuesShort: 'Issues',
    disruptions: 'Disruptions',
    disruptionsShort: 'Work',
    apartments: 'Apartments',
    apartmentsShort: 'Units',
    vehicles: 'Vehicles',
    users: 'Users & Roles',
    usersShort: 'Users',
    invites: 'Invitations',
    invitesShort: 'Invites',
    notices: 'Notices',
    settings: 'Account',
    auditLogs: 'Audit Logs',
    auditShort: 'Audit',
  },
  defaultUserName: 'System User',
  signedOutRole: 'Signed out',
  roleLabels: {
    resident: 'Resident',
    admin: 'Admin',
    superadmin: 'Superadmin',
  },
  signOutTitle: 'Sign Out',
  profile: 'My Profile',
  signOut: 'Sign out',
} as const;
