// Title: Resident Localization
// Path: src/localization/en/resident.ts
// Functionality: English localization strings for resident screens, actions, and empty states.

export const residentDashboard = {
  missingProfileTitle: 'Profile Not Found',
  missingProfileDescription: 'Your authentication account exists, but your resident profile is missing from the system. This usually happens after a database reset or a signup issue.',
  missingProfileContact: 'Please contact property management to have your account set up, then sign in again.',
  missingProfileSignOut: 'Sign out and try again',
  suspendedTitle: 'Access Suspended',
  suspendedDescription: 'Your access has been temporarily suspended by property management. Please contact the administration office.',
  rejectedTitle: 'Access Not Approved',
  rejectedDescription: 'Your account request was not approved, so portal access is unavailable. Please contact the administration office if you believe this is a mistake.',
  pendingTitle: 'Verification in Progress',
  pendingDescription: 'Your account is currently being reviewed. You will have full access to your digital permits once approved.',
  awaitingSignature: 'Awaiting approval',
  welcome: (firstName: string) => `Welcome back, ${firstName}`,
  healthyStatus: 'Everything is looking good today.',
  fallbackResidentName: 'Resident',
  overviewAria: 'Resident account overview',
  identityCardAria: 'Resident identity',
  parkingCardAria: 'Resident parking assignment',
  identityVerified: 'Identity Verified',
  assignedUnit: 'Assigned Unit',
  unitPrefix: 'Unit',
  unitNone: 'None',
  accessLevel: 'Access Level',
  primaryTenant: 'Primary Tenant',
  residentRole: 'Resident',
  portalNoticeTitle: 'Building Notice',
  parkingPassActive: 'Digital Pass Active',
  noAllocation: 'No Allocation',
  spotUnassignedTitle: 'Spot Unassigned',
  spotUnassignedDescription: 'Your apartment currently does not have an active parking spot allocation in the system.',
  secured: 'Secured',
  authorizedAssets: 'Authorized Assets',
  authorizedAssetsDescription: 'Vehicles connected to your apartment and parking access.',
  activeVehicle: 'Active',
  pendingVehicle: 'Pending',
  rejectedVehicle: 'Rejected',
  archivedVehicle: 'Archived',
  unknownVehicleStatus: 'Status unavailable',
  rejectedVehicleDescription: 'Contact property management.',
  noVehiclesTitle: 'No Vehicles Registered',
  noVehiclesDescription: 'You have not registered any vehicles to your unit. Add a vehicle to request parking access from management.',
  viewGarageMap: 'View Garage Map',
  backToDashboard: 'Dashboard',
  overviewParkingSpot: 'Parking Spot',
  overviewSpotUnassigned: 'Unassigned',
  overviewVehicles: 'Registered Vehicles',
  overviewPending: 'Pending Approval',
  overviewAccount: 'Account',
  overviewAccountActive: 'Active',
} as const;

export const residentParkingPage = {
  pageTitle: 'Garage Map',
  mobileNavigationAria: 'Garage navigation',
  sidebarAria: 'Resident parking details',
  assignedSpotLabel: 'Assigned Spot',
  spotBadge: (spotNumber: string) => `Spot ${spotNumber}`,
  vehicleDetailsUnavailable: 'Vehicle details unavailable',
  spotMeta: (floor: string | null, zone: string | null) =>
    `Floor ${floor ?? '-'} - Zone ${zone ?? 'Standard'}`,
} as const;

export const residentParkingMap = {
  unavailableTitle: 'Parking Map Unavailable',
  unavailableDescription: 'Your assigned parking still appears above. The full garage map is being set up and will appear here shortly.',
  title: 'Privacy-Safe Parking Map',
  description: 'You see your own details. Other residents are shown only as occupied.',
  unitPrefix: 'Unit',
  noUnit: 'None',
  visibleAssignment: (count: number) => `${count} visible assignment${count === 1 ? '' : 's'}`,
  street: 'Street',
  floor: (floor: string) => `Floor ${floor}`,
  defaultZone: 'Residential',
  legendTitle: 'Legend',
  legendOwn: 'Your spot',
  yourAssignedSpot: (spotNumber: string) => `${spotNumber} is your assigned spot`,
  spotStatusTitle: (spotNumber: string, status: string) => `${spotNumber} is ${status.toLowerCase()}`,
  registeredVehicle: 'Registered vehicle',
  reportIssue: 'Report Issue',
  temporaryRelocationTitle: 'Temporary relocation active',
  temporaryRelocation: (originalSpot: string, temporarySpot: string) => `Original spot ${originalSpot} to temporary spot ${temporarySpot}.`,
  temporaryRelocationReason: (reason: string) => ` Reason: ${reason}.`,
  pendingSpot: 'pending',
  issueSubmitted: 'Parking issue sent to management.',
  issueSubmitError: 'Parking issue could not be submitted.',
  duplicateActiveIssue: 'You already have an active report for this issue type.',
  modalTitle: 'Report Parking Issue',
  closeIssueDialog: 'Close parking issue form',
  modalDescription: (spotNumber: string) => `Spot ${spotNumber} will be flagged for management review.`,
  issueTypeLabel: 'Issue Type',
  observedPlateLabel: 'Observed Plate',
  observedPlatePlaceholder: 'Optional, e.g. A123BC',
  commentLabel: 'Comment',
  commentPlaceholder: 'Add helpful context for management...',
  reviewNotice: 'This creates a management issue and may temporarily mark your spot for review.',
  cancel: 'Cancel',
  submit: 'Submit Issue',
  submitting: 'Submitting...',
} as const;
